---
template_dir: "/opt/stackstorm/packs/campus_ztp/templates"
excel_file: "/opt/stackstorm/packs/campus_ztp/sample.xlsx"
temp_dir: "/opt/stackstorm/packs/campus_ztp/tmp"
username: "admin"
password: "brocade"
enable_username: "admin"
enable_password: "brocade"
tftp_server: "10.0.0.38"

logging_watch_sensor:
  logging_paths: "/var/log/switches.log"

# List of Boot images per vender, per device type
boot_images:
  Brocade:
    ICX7250: "spz10106.bin"
    ICX7450: "spz10106.bin"
    ICX7750: "swz10106.bin"

# List of Software images per vender, per function, per device type
software_images:
  Brocade:
    ICX7250: "sps08040a.bin"
    ICX7450: "sps08040a.bin"
    ICX7750: "sws08040a.bin"
